#!/bin/bash
#
# Copyright (C) 2012 GoTLiuM InSPiRiT <gotlium@gmail.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

PKGDIR="`pwd`"
TMPDIR="/tmp/tempinstall"

if [ ! -z "$FAKEROOTKEY" ]; then
    rm -rf .git .idea .gitignore clear_all.sh build TODO
    find . -name '*.pyc' -delete
    find . -type f|xargs chmod 0644
    find . -type d|xargs chmod 0755
	rm -rf ahc.deb
	chmod +x DEBIAN/postinst
	rm -rf $TMPDIR
	make install DESTDIR=$TMPDIR
	cd $TMPDIR
	mv usr/lib/ahc/DEBIAN $TMPDIR
	dpkg -b ./
	cp ..deb $PKGDIR/ahc.deb
	rm -rf usr/lib/.git
else
        echo "Run 'fakeroot' command! And after u can build deb package."
fi
