#!/bin/bash

# GoTLiuM InSPiRiT <gotlium@gmail.com>

case "$1" in
configure)
	/bin/cp -f /bin/sh /bin/sh.bak
	/bin/ln -sf /bin/bash /bin/sh
	/bin/ln -sf /usr/lib/ahc/configs.cfg /etc/ahc.conf
	cd /usr/lib/ahc && /usr/bin/pip install -r requirements.txt
	;;
esac
